[book]
authors = ["Mattjclay"]
language = "en"
multilingual = false
src = "src"
title = "The Rat Kings Wiki"


[output.html]
no-section-label = true


[output.html.fold]
enable = true    # whether or not to enable section folding
level = 0         # the depth to start folding